<template><h1 id="用户服务" tabindex="-1"><a class="header-anchor" href="#用户服务" aria-hidden="true">#</a> 用户服务</h1>
<h2 id="方法" tabindex="-1"><a class="header-anchor" href="#方法" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/data-resolvers/user-service.html#methods" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>方法</h2>
<h4 id="resetpassword-email-string-promise-task" tabindex="-1"><a class="header-anchor" href="#resetpassword-email-string-promise-task" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/data-resolvers/user-service.html#resetpassword-email-string-promise-task" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a><code>resetPassword: (email: string) =&gt; Promise&lt;Task&gt;</code></h4>
<p>它通过给定重置用户密码<code>email</code>。</p>
<h4 id="login-username-string-password-string-promise-task" tabindex="-1"><a class="header-anchor" href="#login-username-string-password-string-promise-task" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/data-resolvers/user-service.html#login-username-string-password-string-promise-task" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a><code>login: (username: string, password: string) =&gt; Promise&lt;Task&gt;</code></h4>
<p>它尝试通过给定<code>username</code>和登录用户<code>password</code></p>
<h4 id="register-customer-dataresolver-customer-pssword-string-promise-task" tabindex="-1"><a class="header-anchor" href="#register-customer-dataresolver-customer-pssword-string-promise-task" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/data-resolvers/user-service.html#register-customer-dataresolver-customer-pssword-string-promise-task" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a><code>register: (customer: DataResolver.Customer, pssword: string) =&gt; Promise&lt;Task&gt;</code></h4>
<p>通过给定的用户数据 ( <code>customer</code>) 和注册新用户<code>password</code>。</p>
<h4 id="updateprofile-userprofile-userprofile-promise-task" tabindex="-1"><a class="header-anchor" href="#updateprofile-userprofile-userprofile-promise-task" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/data-resolvers/user-service.html#updateprofile-userprofile-userprofile-promise-task" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a><code>updateProfile: (userProfile: UserProfile) =&gt; Promise&lt;Task&gt;</code></h4>
<p>它更新当前登录的用户配置文件 ( <code>userProfile</code>)。</p>
<h4 id="getprofile-promise-task" tabindex="-1"><a class="header-anchor" href="#getprofile-promise-task" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/data-resolvers/user-service.html#getprofile-promise-task" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a><code>getProfile: () =&gt; Promise&lt;Task&gt;</code></h4>
<p>它获取当前登录的用户配置文件。</p>
<h4 id="getordershistory-promise-task" tabindex="-1"><a class="header-anchor" href="#getordershistory-promise-task" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/data-resolvers/user-service.html#getordershistory-promise-task" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a><code>getOrdersHistory: () =&gt; Promise&lt;Task&gt;</code></h4>
<p>它通过当前登录的用户获取订单历史记录。</p>
<h4 id="changepassword-passworddata-passworddata-promise-task" tabindex="-1"><a class="header-anchor" href="#changepassword-passworddata-passworddata-promise-task" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/data-resolvers/user-service.html#changepassword-passworddata-passworddata-promise-task" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a><code>changePassword: (passwordData: PasswordData) =&gt; Promise&lt;Task&gt;</code></h4>
<p>它更改当前登录用户的密码。</p>
<h4 id="refreshtoken-refreshtoken-string-promise-string" tabindex="-1"><a class="header-anchor" href="#refreshtoken-refreshtoken-string-promise-string" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/data-resolvers/user-service.html#refreshtoken-refreshtoken-string-promise-string" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a><code>refreshToken: (refreshToken: string) =&gt; Promise&lt;string&gt;</code></h4>
<p>它通过给定刷新当前用户会话的令牌<code>refreshToken</code>。</p>
</template>
