<template><h1 id="ssr-缓存" tabindex="-1"><a class="header-anchor" href="#ssr-缓存" aria-hidden="true">#</a> SSR 缓存</h1>
<p>Vue Storefront 生成服务器端呈现的页面和版本以改进 SEO 结果。在最新版本的 Vue Storefront 中，我们为 Vue Storefront 和 Vue Storefront API 添加了输出缓存选项（默认禁用）以提高性能。</p>
<p>小心！</p>
<p>Vue Storefront API 使用与 Vue Storefront 完全相同的输出缓存机制，具有相同的配置和 CLI 界面。</p>
<p>输出缓存由以下<code>config/local.json</code>变量设置：</p>
<div class="language-json ext-json line-numbers-mode"><pre v-pre class="language-json"><code>    <span class="token property">"server"</span><span class="token operator">:</span> <span class="token punctuation">{</span>
      <span class="token property">"host"</span><span class="token operator">:</span> <span class="token string">"localhost"</span><span class="token punctuation">,</span>
      <span class="token property">"port"</span><span class="token operator">:</span> <span class="token number">3000</span><span class="token punctuation">,</span>
      <span class="token property">"protocol"</span><span class="token operator">:</span> <span class="token string">"http"</span><span class="token punctuation">,</span>
      <span class="token property">"api"</span><span class="token operator">:</span> <span class="token string">"api"</span><span class="token punctuation">,</span>
      <span class="token property">"useOutputCacheTagging"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
      <span class="token property">"useOutputCache"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
      <span class="token property">"outputCacheDefaultTtl"</span><span class="token operator">:</span> <span class="token number">86400</span><span class="token punctuation">,</span>
      <span class="token property">"invalidateCacheKey"</span><span class="token operator">:</span> <span class="token string">"aeSu7aip"</span><span class="token punctuation">,</span>
      <span class="token property">"invalidateCacheForwarding"</span><span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span>
      <span class="token property">"invalidateCacheForwardUrl"</span><span class="token operator">:</span> <span class="token string">"http://localhost:8080/invalidate?key=aeSu7aip&amp;tag="</span><span class="token punctuation">,</span>      
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token property">"redis"</span><span class="token operator">:</span> <span class="token punctuation">{</span>
      <span class="token property">"host"</span><span class="token operator">:</span> <span class="token string">"localhost"</span><span class="token punctuation">,</span>
      <span class="token property">"port"</span><span class="token operator">:</span> <span class="token number">6379</span><span class="token punctuation">,</span>
      <span class="token property">"db"</span><span class="token operator">:</span> <span class="token number">0</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br></div></div><h2 id="动态标签" tabindex="-1"><a class="header-anchor" href="#动态标签" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/ssr-cache.html#dynamic-tags" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>动态标签</h2>
<p>动态标签配置选项：<code>useOutputCacheTagging</code>- 如果设置为<code>true</code>，Vue Storefront 将生成特殊的 HTTP 标头<code>X-VS-Cache-Tags</code></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>res<span class="token punctuation">.</span><span class="token function">setHeader</span><span class="token punctuation">(</span><span class="token string">'X-VS-Cache-Tags'</span><span class="token punctuation">,</span> cacheTags<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>缓存标签是根据特定页面上使用的产品和类别分配的。一个典型的<code>X-VS-Cache-Tags</code>标签如下所示：</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>X-VS-Cache-Tags: P1852 P198 C20
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>如果您正在使用 Varnish 缓存，则标签可用于使其无效。<a href="https://www.drupal.org/docs/8/api/cache-api/cache-tags-varnish" target="_blank" rel="noopener noreferrer">阅读更多 （打开新窗口）<OutboundLink/></a>.</p>
<h2 id="redis" tabindex="-1"><a class="header-anchor" href="#redis" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/ssr-cache.html#redis" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>Redis</h2>
<p>如果<code>useOutputCache</code>和<code>useOutputCacheTagging</code>选项都设置为<code>true</code>，则 Vue Storefront 使用存储在 Redis 中的输出缓存（在配置文件的 redis 部分配置）。缓存使用动态标签进行标记，可以使用特殊的 webhook 使其失效：</p>
<p>清除包含特定产品和类别的所有页面的示例调用：</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">curl</span> http://localhost:3000/invalidate?tag<span class="token operator">=</span>P1852,C20
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>清除所有产品、类别和主页的示例调用：</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">curl</span> http://localhost:3000/invalidate?tag<span class="token operator">=</span>product,category,home
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>小心！</p>
<p>我们强烈建议您不要在开发模式下使用输出缓存。通过使用它，您将无法在修改 Vue 组件等后刷新 UI 更改。</p>
<h2 id="cli-缓存清除" tabindex="-1"><a class="header-anchor" href="#cli-缓存清除" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/ssr-cache.html#cli-cache-clear" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>CLI 缓存清除</h2>
<p>您可以通过运行以下命令手动清除特定标签的 Redis 缓存：</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">yarn</span> run cache <span class="token function">clear</span>
<span class="token function">yarn</span> run cache <span class="token function">clear</span> -- --tag<span class="token operator">=</span>product,category
<span class="token function">yarn</span> run cache <span class="token function">clear</span> -- --tag<span class="token operator">=</span>P198
<span class="token function">yarn</span> run cache <span class="token function">clear</span> -- --tag<span class="token operator">=</span>*
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><p>**注意：**上述命令在<code>vue-storefront-api</code>.</p>
<p>可用标签键的设置<code>config.server.availableCacheTags</code>（默认：<code>&quot;product&quot;, &quot;category&quot;, &quot;home&quot;, &quot;checkout&quot;, &quot;page-not-found&quot;, &quot;compare&quot;, &quot;my-account&quot;, &quot;P&quot;, &quot;C&quot;</code>）</p>
<p><strong>动态缓存失效：</strong><a href="https://github.com/vuestorefront/mage2vuestorefront" target="_blank" rel="noopener noreferrer">mage2vuestorefront 的<OutboundLink/></a>最新版本<a href="https://github.com/vuestorefront/mage2vuestorefront" target="_blank" rel="noopener noreferrer"> （打开新窗口）<OutboundLink/></a>支持输出缓存失效。输出缓存标有产品和类别 ID（特定页面上使用的产品和类别）。如果您设置以下 ENV 变量，Mage2vuestorefront 可以使产品和类别页面的缓存无效：</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token builtin class-name">export</span> <span class="token assign-left variable">VS_INVALIDATE_CACHE_URL</span><span class="token operator">=</span>http://localhost:3000/invalidate?key<span class="token operator">=</span>SECRETKEY<span class="token operator">&amp;</span><span class="token assign-left variable">tag</span><span class="token operator">=</span>
<span class="token builtin class-name">export</span> <span class="token assign-left variable">VS_INVALIDATE_CACHE</span><span class="token operator">=</span><span class="token number">1</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>小心！</p>
<p>所有官方 Vue Storefront 数据索引器，包括<a href="https://github.com/vuestorefront/magento1-vsbridge-indexer" target="_blank" rel="noopener noreferrer">magento1-vsbridge-indexer （打开新窗口）<OutboundLink/></a>和<a href="https://github.com/vuestorefront/magento2-vsbridge-indexer" target="_blank" rel="noopener noreferrer">magento2-vsbridge-indexer （打开新窗口）<OutboundLink/></a>支持缓存失效。如果在 API 和 Vue Storefront 前端应用程序中都启用了缓存，请确保您正确使用了<code>config.server.invalidateCacheForwardUrl</code>config 变量，因为索引器只能将缓存无效请求发送到一个 URL（前端或后端）并且应该转发。请检查 中的默认转发 URL<code>default.json</code>并将<code>key</code>参数调整为 的值<code>server.invalidateCacheKey</code>。</p>
<p>对于<code>magento1-vsbridge-indexer</code>并且<code>magento2-vsbridge-indexer</code>请在 Magento 管理面板中使用正确的设置。</p>
<p>安全注意事项</p>
<p>请注意，<code>key=SECRETKEY</code>应等于的<code>vue-storefront/config/local.json</code>值<code>server.invalidateCacheKey</code></p>
<h2 id="添加新类型-缓存标签" tabindex="-1"><a class="header-anchor" href="#添加新类型-缓存标签" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/ssr-cache.html#adding-new-types-cache-tags" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>添加新类型/缓存标签</h2>
<p>如果您要添加新类型的页面 ( <code>core/pages</code>) 和<code>config.server.useOutputCache=true</code>，您还应该扩展<code>config.server.availableCacheTags</code>新的通用标签，该标签将与与此新页面连接的 URL 连接。</p>
<p>这样做之后，请将该<code>asyncData</code>方法添加到您的页面代码中以分配正确的标签（<code>core/pages/Home.js</code>例如请看一下）：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>  <span class="token function">asyncData</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> store<span class="token punctuation">,</span> route<span class="token punctuation">,</span> context <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span> <span class="token comment">// this is for SSR purposes to prefetch data</span>
    <span class="token keyword">return</span> <span class="token keyword">new</span> <span class="token class-name">Promise</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">resolve<span class="token punctuation">,</span> reject</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
      <span class="token keyword">if</span> <span class="token punctuation">(</span>context<span class="token punctuation">)</span> context<span class="token punctuation">.</span>output<span class="token punctuation">.</span>cacheTags<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">home</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span>
      Logger<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'Entering asyncData for Home root '</span> <span class="token operator">+</span> <span class="token keyword">new</span> <span class="token class-name">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
      EventBus<span class="token punctuation">.</span><span class="token function">$emitFilter</span><span class="token punctuation">(</span><span class="token string">'home-after-load'</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> store<span class="token operator">:</span> store<span class="token punctuation">,</span> route<span class="token operator">:</span> route <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">results</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
        <span class="token keyword">return</span> <span class="token function">resolve</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
      <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">catch</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">err</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
        Logger<span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span>err<span class="token punctuation">)</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token function">reject</span><span class="token punctuation">(</span>err<span class="token punctuation">)</span>
      <span class="token punctuation">}</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br></div></div><p>这一行：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">if</span> <span class="token punctuation">(</span>context<span class="token punctuation">)</span> context<span class="token punctuation">.</span>output<span class="token punctuation">.</span>cacheTags<span class="token punctuation">.</span><span class="token function">add</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">home</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>负责分配具有当前 HTTP 请求输出的特定标签。</p>
<h2 id="生产缓存策略" tabindex="-1"><a class="header-anchor" href="#生产缓存策略" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/ssr-cache.html#caching-strategies-on-production" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>生产缓存策略</h2>
<p>当谈到生产缓存时，我们在<em>Vue Storefront</em>基础设施的每一层都做了一组缓存。我们的指南中有一个关于<a href="https://docs.vuestorefront.io/v1/guide/installation/production-setup.html" target="_blank" rel="noopener noreferrer"><em>生产设置</em><OutboundLink/></a>的部分。另外阅读<a href="https://medium.com/the-vue-storefront-journal/caching-on-production-10b00a5614f8" target="_blank" rel="noopener noreferrer">这篇文章 （打开新窗口）<OutboundLink/></a>更多细节。</p>
</template>
