<template><h1 id="常见问题和解决方案" tabindex="-1"><a class="header-anchor" href="#常见问题和解决方案" aria-hidden="true">#</a> 常见问题和解决方案</h1>
<p>在下面，您可以找到最常见问题的解决方案以及 Vue Storefront 所需的典型配置更改的建议。如果您自己解决了任何新问题，请在<a href="http://vuestorefront.slack.com/" target="_blank" rel="noopener noreferrer">Slack<OutboundLink/></a>上告诉我们<a href="http://vuestorefront.slack.com/" target="_blank" rel="noopener noreferrer"> （打开新窗口）<OutboundLink/></a>我们会将它们添加到列表中，这样其他人就不需要重新发明轮子了。</p>
<h2 id="安装-vue-storefront-时启动-docker-的问题" tabindex="-1"><a class="header-anchor" href="#安装-vue-storefront-时启动-docker-的问题" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/recipes.html#problem-starting-docker-while-installing-vue-storefront" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>安装 vue-storefront 时启动 Docker 的问题</h2>
<p>如果您收到以下错误：</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>┌────────────────────────────────────────────────────────────────────────────┐
│ ERROR                                                                      │
│                                                                            │
│ Can't start Docker in background.                                          │
│                                                                            │
│ Please check log file for details: /tmp/vue-storefront/var/log/install.log │
└────────────────────────────────────────────────────────────────────────────┘
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><p>请检查：</p>
<ul>
<li>如果有<code>docker-compose</code>可用的命令。如果没有，请安装它；</li>
<li>请检查<code>docker-compose up -d</code>在<code>vue-storefront-api</code>实例内手动运行的输出。在某些生产环境中，Docker 对超级用户是有限制的，在很多情况下只是<code>/var/run/docker.sock</code>更改权限的问题（例如更改为 755）</li>
</ul>
<h2 id="产品未显示-illegal-argument-exception" tabindex="-1"><a class="header-anchor" href="#产品未显示-illegal-argument-exception" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/recipes.html#product-not-displayed-illegal-argument-exception" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>产品未显示（illegal_argument_exception）</h2>
<p>在的情况下</p>
<div class="language-json ext-json line-numbers-mode"><pre v-pre class="language-json"><code><span class="token punctuation">{</span>
  <span class="token property">"root_cause"</span><span class="token operator">:</span> <span class="token punctuation">[</span>
    <span class="token punctuation">{</span>
      <span class="token property">"type"</span><span class="token operator">:</span> <span class="token string">"illegal_argument_exception"</span><span class="token punctuation">,</span>
      <span class="token property">"reason"</span><span class="token operator">:</span> <span class="token string">"Fielddata is disabled on text fields by default. Set fielddata=true on [created_at] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">]</span><span class="token punctuation">,</span>
  <span class="token property">"type"</span><span class="token operator">:</span> <span class="token string">"search_phase_execution_exception"</span><span class="token punctuation">,</span>
  <span class="token property">"reason"</span><span class="token operator">:</span> <span class="token string">"all shards failed"</span><span class="token punctuation">,</span>
  <span class="token property">"phase"</span><span class="token operator">:</span> <span class="token string">"query"</span><span class="token punctuation">,</span>
  <span class="token property">"grouped"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
  <span class="token property">"failed_shards"</span><span class="token operator">:</span> <span class="token punctuation">[</span>
    <span class="token punctuation">{</span>
      <span class="token property">"shard"</span><span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span>
      <span class="token property">"index"</span><span class="token operator">:</span> <span class="token string">"vue_storefront_catalog_1521776807"</span><span class="token punctuation">,</span>
      <span class="token property">"node"</span><span class="token operator">:</span> <span class="token string">"xIOeZW2lTwaprGXh6YLyCA"</span><span class="token punctuation">,</span>
      <span class="token property">"reason"</span><span class="token operator">:</span> <span class="token punctuation">{</span>
        <span class="token property">"type"</span><span class="token operator">:</span> <span class="token string">"illegal_argument_exception"</span><span class="token punctuation">,</span>
        <span class="token property">"reason"</span><span class="token operator">:</span> <span class="token string">"Fielddata is disabled on text fields by default. Set fielddata=true on [created_at] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">]</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br></div></div><p>见<a href="https://github.com/vuestorefront/vue-storefront/issues/137" target="_blank" rel="noopener noreferrer">#137 中<OutboundLink/></a>的讨论<a href="https://github.com/vuestorefront/vue-storefront/issues/137" target="_blank" rel="noopener noreferrer"> （打开新窗口）<OutboundLink/></a>. 另请检查<a href="https://github.com/vuestorefront/vue-storefront/blob/master/docs/guide/data/database-tool.md" target="_blank" rel="noopener noreferrer">数据库工具（打开新窗口）<OutboundLink/></a></p>
<h2 id="尝试从-api-检索详细产品信息时出现-http-400-cors-错误" tabindex="-1"><a class="header-anchor" href="#尝试从-api-检索详细产品信息时出现-http-400-cors-错误" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/recipes.html#http-400-cors-errors-when-trying-to-retrieve-detailed-product-information-from-api" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>尝试从 API 检索详细产品信息时出现 HTTP 400 / CORS 错误</h2>
<p>如果所有其他请求都正常工作，那么很可能您的产品具有太多属性。所有这些都包含在通过 GET 请求发送的 ElasticSearch 查询中，这可能会变得太长。尝试限制已编入索引并稍后用于此产品视图的属性数量。</p>
<p>此答案<a href="https://github.com/vuestorefront/vue-storefront/issues/2167" target="_blank" rel="noopener noreferrer">在解决此问题<OutboundLink/></a>之前有效<a href="https://github.com/vuestorefront/vue-storefront/issues/2167" target="_blank" rel="noopener noreferrer"> （打开新窗口）<OutboundLink/></a>.</p>
<h2 id="在自定义开发中使用-git-的推荐方法是什么" tabindex="-1"><a class="header-anchor" href="#在自定义开发中使用-git-的推荐方法是什么" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/recipes.html#what-s-the-recommended-way-to-use-git-on-custom-development" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>在自定义开发中使用 git 的推荐方法是什么</h2>
<p>一种选择是进行某种分叉，或者只是将整个 repo 发送到您的 git 服务。然后，如果您想做一些 VS 更新，您可能只需要从我们的起源中提取更改。一旦我们设法将核心分离为 npm 模块，另一个选项将可用。</p>
<h2 id="如何将自定义可配置属性添加到产品页面" tabindex="-1"><a class="header-anchor" href="#如何将自定义可配置属性添加到产品页面" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/recipes.html#how-to-add-custom-configurable-attributes-to-the-product-page" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>如何将自定义可配置属性添加到产品页面</h2>
<p>我们可以在哪里为产品添加过滤器和额外的可配置选项？我刚刚添加了 iPhone X 作为示例，我想添加存储作为选项。</p>
<p><img src="https://docs.vuestorefront.io/v1/assets/img/Apple_iPhone_X.26ba0e2c.png" alt="如何添加额外的自定义属性？"></p>
<p>为此，您需要修改主题，更改以下代码段：</p>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>row top-xs m0 pt15 pb40 variants-wrapper<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">v-if</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>option.label == <span class="token punctuation">'</span>Color<span class="token punctuation">'</span><span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>color-button</span>
      <span class="token attr-name">v-for</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>(c, i) in options.color<span class="token punctuation">"</span></span>
      <span class="token attr-name">:key</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>i<span class="token punctuation">"</span></span>
      <span class="token attr-name">:id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>c.id<span class="token punctuation">"</span></span>
      <span class="token attr-name">:label</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>c.label<span class="token punctuation">"</span></span>
      <span class="token attr-name">context</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>product<span class="token punctuation">"</span></span>
      <span class="token attr-name">code</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>color<span class="token punctuation">"</span></span>
      <span class="token attr-name">:class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>{ active: c.id == configuration.color.id }<span class="token punctuation">"</span></span>
    <span class="token punctuation">/></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>sizes<span class="token punctuation">"</span></span> <span class="token attr-name">v-if</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>option.label == <span class="token punctuation">'</span>Size<span class="token punctuation">'</span><span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>size-button</span>
      <span class="token attr-name">v-for</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>(s, i) in options.size<span class="token punctuation">"</span></span>
      <span class="token attr-name">:key</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>i<span class="token punctuation">"</span></span>
      <span class="token attr-name">:id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>s.id<span class="token punctuation">"</span></span>
      <span class="token attr-name">:label</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>s.label<span class="token punctuation">"</span></span>
      <span class="token attr-name">context</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>product<span class="token punctuation">"</span></span>
      <span class="token attr-name">code</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>size<span class="token punctuation">"</span></span>
      <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>mr10 mb10<span class="token punctuation">"</span></span>
      <span class="token attr-name">:class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>{ active: s.id == configuration.size.id }<span class="token punctuation">"</span></span>
      <span class="token attr-name">v-focus-clean</span>
    <span class="token punctuation">/></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br></div></div><p>您必须为其他可配置属性添加 UI 控件。</p>
<h2 id="添加到购物车-在产品页面上时-产品名称更改为-sku" tabindex="-1"><a class="header-anchor" href="#添加到购物车-在产品页面上时-产品名称更改为-sku" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/recipes.html#product-name-changed-to-sku-when-adding-to-cart-on-the-product-page" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>添加到购物车/在产品页面上时，产品名称更改为 SKU</h2>
<p>默认情况下，当用户在产品<code>Product.vue</code>页面上选择任何特定的产品变体时<code>configurable</code>，标题、图片、价格等属性将更改为相应的<code>simple</code>（在 内<code>product.configurable_children</code>）。如果在 Magento 面板中，变体的产品名称设置为 SKU 或其他任何内容，则正确的行为是在选择变体时产品名称更改为它。</p>
<p>要纠正此行为，您可以：</p>
<ul>
<li>修改<a href="https://github.com/vuestorefront/vue-storefront/blob/6a5a569a7e96703b865f841dabbe3c6a1020b3ab/core/store/modules/product/actions.js#L311" target="_blank" rel="noopener noreferrer">核心 （打开新窗口）<OutboundLink/></a>- 从 中过滤出<code>name</code>属性<code>Object.assign</code>，它负责从变体 -&gt; 当前产品中复制属性。</li>
<li>修改<code>mage2vuestorefront</code>进口商以更正<code>configurable_children</code> <a href="https://github.com/vuestorefront/mage2vuestorefront/blob/ca0c4723530b148cfdfb99784168af529e39d599/src/adapters/magento/product.js#L167" target="_blank" rel="noopener noreferrer">产品名称 （打开新窗口）<OutboundLink/></a>.</li>
<li>使用绑定到<code>EventBus.$emitFilter('product-after-single', { key: key, options: options, product: products[0] })</code>事件并修改<code>product.configurable_children</code>属性：</li>
</ul>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>  <span class="token keyword">if</span> <span class="token punctuation">(</span>product<span class="token punctuation">.</span>configurable_children<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">let</span> configurableChild <span class="token keyword">of</span> product<span class="token punctuation">.</span>configurable_children<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        configurableChild<span class="token punctuation">.</span>name <span class="token operator">=</span> product<span class="token punctuation">.</span>name
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><h2 id="如何使动态价格起作用-目录规则" tabindex="-1"><a class="header-anchor" href="#如何使动态价格起作用-目录规则" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/recipes.html#how-to-get-dynamic-prices-to-work-catalog-rules" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>如何使动态价格起作用（目录规则）</h2>
<p>按照有关<a href="https://docs.vuestorefront.io/v1/guide/installation/magento.html" target="_blank" rel="noopener noreferrer">如何连接到 Magento2<OutboundLink/></a>的教程之后，价格会在手动运行<a href="https://github.com/vuestorefront/mage2vuestorefront" target="_blank" rel="noopener noreferrer">mage2vuestorefront cli 命令<OutboundLink/></a>后更新<a href="https://github.com/vuestorefront/mage2vuestorefront" target="_blank" rel="noopener noreferrer"> （打开新窗口）<OutboundLink/></a>.</p>
<p>但是，可以选择动态获取价格。为此，您必须<code>conf/local.json</code>从默认 ( <code>conf/default.json</code>)更改内部配置：</p>
<div class="language-json ext-json line-numbers-mode"><pre v-pre class="language-json"><code>  <span class="token property">"products"</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token property">"preventConfigurableChildrenDirectAccess"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
    <span class="token property">"alwaysSyncPlatformPricesOver"</span><span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span>
    <span class="token property">"clearPricesBeforePlatformSync"</span><span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span>
    <span class="token property">"waitForPlatformSync"</span><span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span>
    <span class="token property">"endpoint"</span><span class="token operator">:</span> <span class="token string">"http://localhost:8080/api/product"</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><p>到：</p>
<div class="language-json ext-json line-numbers-mode"><pre v-pre class="language-json"><code>  <span class="token property">"products"</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token property">"preventConfigurableChildrenDirectAccess"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
    <span class="token property">"alwaysSyncPlatformPricesOver"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
    <span class="token property">"clearPricesBeforePlatformSync"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
    <span class="token property">"waitForPlatformSync"</span><span class="token operator">:</span> <span class="token boolean">false</span><span class="token punctuation">,</span>
    <span class="token property">"endpoint"</span><span class="token operator">:</span> <span class="token string">"http://localhost:8080/api/product"</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><p>要使其工作，您需要在<code>vue-storefront-api</code>- 中配置 Magento 2 Oauth 密钥<code>conf/local.json</code>。他的变化意味着每次显示产品列表时，VS 都会直接从 Magento 获取最新价格，而无需重新索引 Elasticsearch。</p>
<h2 id="没有找到产品-在节点-harmony-cli-js-fullreindex-之后" tabindex="-1"><a class="header-anchor" href="#没有找到产品-在节点-harmony-cli-js-fullreindex-之后" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/recipes.html#no-products-found-after-node-harmony-cli-js-fullreindex" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>没有找到产品！在节点 --harmony cli.js fullreindex 之后</h2>
<p>看一下<a href="https://github.com/vuestorefront/vue-storefront/issues/644" target="_blank" rel="noopener noreferrer">#644<OutboundLink/></a>的讨论<a href="https://github.com/vuestorefront/vue-storefront/issues/644" target="_blank" rel="noopener noreferrer"> （打开新窗口）<OutboundLink/></a>长话短说，您需要在<code>mage2nosql</code>项目中运行以下命令：</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code>node cli.js products --partitions<span class="token operator">=</span><span class="token number">1</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h2 id="如何将产品购物车与-magento-同步以启动并运行购物车促销规则" tabindex="-1"><a class="header-anchor" href="#如何将产品购物车与-magento-同步以启动并运行购物车促销规则" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/recipes.html#how-to-sync-the-products-cart-with-magento-to-get-the-cart-promo-rules-up-and-running" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>如何将产品购物车与 Magento 同步以启动并运行购物车促销规则</h2>
<p>要在 Magento 计算所有折扣和税金后显示正确的价格和总数，您需要修改<code>conf/local.json</code>配置（作为参考，请查看<code>conf/default.json</code>），添加一个附加部分：</p>
<div class="language-json ext-json line-numbers-mode"><pre v-pre class="language-json"><code>  <span class="token property">"cart"</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token property">"synchronize"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
    <span class="token property">"synchronize_totals"</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
    <span class="token property">"create_endpoint"</span><span class="token operator">:</span> <span class="token string">"http://localhost:8080/api/cart/create?token={{token}}"</span><span class="token punctuation">,</span>
    <span class="token property">"updateitem_endpoint"</span><span class="token operator">:</span> <span class="token string">"http://localhost:8080/api/cart/update?token={{token}}&amp;cartId={{cartId}}"</span><span class="token punctuation">,</span>
    <span class="token property">"deleteitem_endpoint"</span><span class="token operator">:</span> <span class="token string">"http://localhost:8080/api/cart/delete?token={{token}}&amp;cartId={{cartId}}"</span><span class="token punctuation">,</span>
    <span class="token property">"pull_endpoint"</span><span class="token operator">:</span> <span class="token string">"http://localhost:8080/api/cart/pull?token={{token}}&amp;cartId={{cartId}}"</span><span class="token punctuation">,</span>
    <span class="token property">"totals_endpoint"</span><span class="token operator">:</span> <span class="token string">"http://localhost:8080/api/cart/totals?token={{token}}&amp;cartId={{cartId}}"</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><p>要使其工作，您需要在<code>vue-storefront-api</code>- 中配置 Magento 2 OAuth 密钥<code>conf/local.json</code>。</p>
<p>在此更改后，您需要重新启动<code>yarn dev</code>命令以让 VS 考虑配置更改。所有购物车操作（添加到购物车、从购物车中删除、修改数量）现在都直接与 Magento 2 同步，用于访客和登录客户端。</p>
<h2 id="如何整合第三方平台-您认为它可以与传统的定制-php-电子商务一起使用吗" tabindex="-1"><a class="header-anchor" href="#如何整合第三方平台-您认为它可以与传统的定制-php-电子商务一起使用吗" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/recipes.html#how-to-integrate-3rd-party-platform-do-you-think-it-could-be-used-with-a-legacy-bespoke-php-ecommerce" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>如何整合第三方平台？您认为它可以与传统的定制 PHP 电子商务一起使用吗？</h2>
<p>是的，我相信可以。您应该根据我们的<a href="https://docs.vuestorefront.io/v1/guide/extensions/extending-api.html" target="_blank" rel="noopener noreferrer">规范<OutboundLink/></a>公开 API，第二步是<a href="https://medium.com/@piotrkarwatka/how-to-connect-3rd-party-platform-to-vue-storefront-df9cb30779f6" target="_blank" rel="noopener noreferrer">创建数据桥 （打开新窗口）<OutboundLink/></a>使用当前目录数据填充 ElasticSearch。</p>
<h2 id="是否有任何关于集成支付网关的文档" tabindex="-1"><a class="header-anchor" href="#是否有任何关于集成支付网关的文档" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/recipes.html#is-there-any-documentation-on-integrating-payment-gateways" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>是否有任何关于集成支付网关的文档？</h2>
<p>我们正在研究一种支付模块的样板。现在，请看一个<a href="https://github.com/develodesign/vue-storefront-stripe" target="_blank" rel="noopener noreferrer">活生生的例子 （打开新窗口）<OutboundLink/></a>并尝试遵循那里的设计模式。样板和文档将出现的任务是<a href="https://github.com/vuestorefront/vue-storefront/issues/923" target="_blank" rel="noopener noreferrer">https://github.com/vuestorefront/vue-storefront/issues/923 （打开新窗口）<OutboundLink/></a>.</p>
<h2 id="是否有任何国际化支持" tabindex="-1"><a class="header-anchor" href="#是否有任何国际化支持" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/recipes.html#is-there-any-internationalization-support" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>是否有任何国际化支持？</h2>
<p>是的，我们已经默认支持七种语言（EN、FR、ES、RU、JP、NL、DE）和<a href="https://docs.vuestorefront.io/v1/guide/core-themes/translations.html" target="_blank" rel="noopener noreferrer">翻译文档<OutboundLink/></a>。</p>
<p>货币是在<code>local.json</code>配置文件中设置的，并且（连同语言）是针对每个实例设置的，因此如果您支持多种语言和国家/地区，则需要（就目前而言）运行几个单独的实例。</p>
<h2 id="如果网站上有-10k-个产品-当您第一次在移动设备上浏览网站时-它会产生高带宽下载吗" tabindex="-1"><a class="header-anchor" href="#如果网站上有-10k-个产品-当您第一次在移动设备上浏览网站时-它会产生高带宽下载吗" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/recipes.html#if-10k-products-are-on-the-site-will-it-create-a-high-bandwidth-download-when-you-navigate-the-site-for-the-first-time-on-a-mobile-device" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>如果网站上有 10k 个产品，当您第一次在移动设备上浏览网站时，它会产生高带宽下载吗？</h2>
<p>不必要。Vue Storefront 从浏览的类别中缓存产品。这是默认的解决方案，可以通过修改来改变<code>core/store/lib/search.js</code></p>
<h2 id="如何在-elasticsearch-模式中添加-删除-更改字段类型" tabindex="-1"><a class="header-anchor" href="#如何在-elasticsearch-模式中添加-删除-更改字段类型" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/recipes.html#how-to-add-remove-change-field-types-in-the-elasticsearch-schema" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>如何在 Elasticsearch 模式中添加/删除/更改字段类型</h2>
<p>它是通过数据库工具架构更改完成的。请按照<a href="https://docs.vuestorefront.io/v1/guide/data/database-tool.html#chaning-the-index-structure--adding-new-fields--chaning-the-types" target="_blank" rel="noopener noreferrer">数据库工具手册中<OutboundLink/></a>的说明进行<a href="https://docs.vuestorefront.io/v1/guide/data/database-tool.html#chaning-the-index-structure--adding-new-fields--chaning-the-types" target="_blank" rel="noopener noreferrer">操作<OutboundLink/></a>。</p>
<h2 id="如何集成第-3-方-magento-扩展" tabindex="-1"><a class="header-anchor" href="#如何集成第-3-方-magento-扩展" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/recipes.html#how-to-integrate-3rd-party-magento-extensions" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>如何集成第 3 方 Magento 扩展</h2>
<p>不幸的是，Magento 扩展尚未与任何可用的 PWA 解决方案兼容。所以如果你想集成一些现有的扩展，最简单的方法是：</p>
<ul>
<li>通过一些 Magento 2 REST API 端点公开数据。</li>
<li>使用 Vuex store 消费 VS 中的端点；在 Vue Storefront 中<a href="https://docs.vuestorefront.io/v1/guide/vuex/introduction.html" target="_blank" rel="noopener noreferrer">阅读更多<OutboundLink/></a>关于 Vuex 的信息。</li>
<li>在 VS 中实现 UI。</li>
</ul>
<p>如果扩展没有使用用户界面，它们可能会立即与 VS 一起使用，因为我们使用标准的 Magento 2 API 调用进行集成部分。</p>
<h2 id="如何支持多商店-多网站设置" tabindex="-1"><a class="header-anchor" href="#如何支持多商店-多网站设置" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/recipes.html#how-to-support-multistore-multi-website-setup" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>如何支持多商店/多网站设置</h2>
<p>有关详细信息，请查看<a href="https://docs.vuestorefront.io/v1/guide/integrations/multistore.html" target="_blank" rel="noopener noreferrer">Multistore 设置<OutboundLink/></a>指南</p>
<h2 id="如何处理基于configurable-children的category过滤器" tabindex="-1"><a class="header-anchor" href="#如何处理基于configurable-children的category过滤器" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/recipes.html#how-to-deal-with-category-filters-based-on-configurable-children" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>如何处理基于configurable_children的Category过滤器</h2>
<p>如果您希望使用可配置产品的类别过滤器，则需要扩展<code>product.configurable_children.attrName</code>to<code>product.attrName_options</code>数组。这是由<a href="https://github.com/vuestorefront/mage2vuestorefront" target="_blank" rel="noopener noreferrer">mage2vuestorefront<OutboundLink/></a>自动完成的<a href="https://github.com/vuestorefront/mage2vuestorefront" target="_blank" rel="noopener noreferrer"> （打开新窗口）<OutboundLink/></a>对于设置为<code>product.configurable_options</code>（默认情况下：颜色、大小）的所有属性。如果要向<code>manufacturer</code>过滤器添加其他字段，则需要展开<code>product.manufacturer_options</code>字段。这样做最简单的方法是设置<code>config.product.expandConfigurableFilters</code>到<code>['manufacturer']</code>并重新运行<code>mage2vuestorefront</code>索引。</p>
<h2 id="如何将原始-magento2-url-重定向到-vue-storefront" tabindex="-1"><a class="header-anchor" href="#如何将原始-magento2-url-重定向到-vue-storefront" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/recipes.html#how-to-redirect-original-magento2-urls-to-vue-storefront" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>如何将原始 Magento2 URL 重定向到 Vue Storefront</h2>
<p>有一个 NGINX 的 SEO 重定向生成器 -&gt;<code>https://serverfault.com/a/441517</code>在<a href="https://github.com/vuestorefront/vue-storefront-api/commit/2c7e10b4c4294f222f7a1aae96627d6a0e23f30e" target="_blank" rel="noopener noreferrer">vue-storefront-api 中<OutboundLink/></a>可用<a href="https://github.com/vuestorefront/vue-storefront-api/commit/2c7e10b4c4294f222f7a1aae96627d6a0e23f30e" target="_blank" rel="noopener noreferrer"> （打开新窗口）<OutboundLink/></a>. 现在，您可以生成一个 SEO 地图，通过运行以下命令将用户从原始 Magento URL 重定向到 Vue Storefront URL：</p>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">yarn</span> seo redirects — —oldFormat<span class="token operator">=</span>true <span class="token operator">|</span> <span class="token boolean">false</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>请确保<code>vue-storefront/config/local.json</code>设定的<code>useMagentoUrlKeys</code>设置为<code>true</code>和你有ElasticSearch使用当前版本的Magento2实例同步<a href="https://github.com/vuestorefront/mage2vuestorefront" target="_blank" rel="noopener noreferrer">mage2vuestorefront （打开新窗口）<OutboundLink/></a>.</p>
<p>**请注意：**作为<code>url_key</code>字段在类别集合中必须是唯一的。因此，我们默认根据名称和类别 ID 生成其值。请<a href="https://github.com/vuestorefront/mage2vuestorefront/#initial-vue-storefront-import" target="_blank" rel="noopener noreferrer">关闭此选项 （打开新窗口）<OutboundLink/></a>如果你想保留<code>url_key</code>它们来自 Magento2。</p>
<h2 id="当点击-api-将可配置的产品添加到购物车时-您需要为您的项目消息选择选项" tabindex="-1"><a class="header-anchor" href="#当点击-api-将可配置的产品添加到购物车时-您需要为您的项目消息选择选项" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/recipes.html#you-need-to-choose-options-for-your-item-message-when-hit-api-for-add-to-cart-a-configurable-product" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>当点击 API 将可配置的产品添加到购物车时，您需要为您的项目消息选择选项</h2>
<p>这是因为演示数据转储适用于<code>demo-magento2.vuestorefront.io</code>实例属性 ID。请使用<a href="https://github.com/vuestorefront/mage2vuestorefront" target="_blank" rel="noopener noreferrer">mage2vuestorefront<OutboundLink/></a>重新导入所有产品数据<a href="https://github.com/vuestorefront/mage2vuestorefront" target="_blank" rel="noopener noreferrer">（打开新窗口）<OutboundLink/></a></p>
<h2 id="添加自定义类别过滤器" tabindex="-1"><a class="header-anchor" href="#添加自定义类别过滤器" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/recipes.html#adding-custom-category-filters" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>添加自定义类别过滤器</h2>
<p>您需要将要显示的属性添加到<code>config/local.json</code>字段名称中<code>products.defaultFilters</code>：：</p>
<div class="language-json ext-json line-numbers-mode"><pre v-pre class="language-json"><code><span class="token property">"defaultFilters"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">"color"</span><span class="token punctuation">,</span> <span class="token string">"size"</span><span class="token punctuation">,</span> <span class="token string">"price"</span><span class="token punctuation">,</span> <span class="token string">"erin_recommends"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>然后您可以<a href="https://github.com/vuestorefront/vue-storefront/blob/49dc8a2dc9326e9e83d663cc27f8bb0688525f13/src/themes/default/components/core/blocks/Category/Sidebar.vue" target="_blank" rel="noopener noreferrer">在此处<OutboundLink/></a>为每个单独的过滤器使用适当的控件<a href="https://github.com/vuestorefront/vue-storefront/blob/49dc8a2dc9326e9e83d663cc27f8bb0688525f13/src/themes/default/components/core/blocks/Category/Sidebar.vue" target="_blank" rel="noopener noreferrer"> （打开新窗口）<OutboundLink/></a>.</p>
<h2 id="将所有-vsf-i18n-短语收集到一个-csv-文件中" tabindex="-1"><a class="header-anchor" href="#将所有-vsf-i18n-短语收集到一个-csv-文件中" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/recipes.html#collecting-all-vsf-i18n-phrases-into-a-csv" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>将所有 VSF i18n 短语收集到一个 CSV 文件中</h2>
<p>将整个项目翻译成外语可能非常耗时。一个好的开始是将所有 i18n 短语正确收集到一个 CSV 文件中。以下 bash 代码行将完成工作（将创建名为 i18n.csv 的管道分隔 CSV 文件，根据您的需要进行相应调整）。</p>
<p>在项目的根文件夹上执行以下行：</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>grep --include \*.js --include \*.vue -nrw ./ -e 'i18n.t(' -e '$t(' -h | grep -o -P "(?&lt;=t\(\').*(?=\'\))" | awk -F"'" -v OFS='|' '{ print $1,$1 }' > i18n.csv
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>该代码基本上看起来为全部所有项目文件<code>i18n.t('some string')</code>和<code>$t('some string')</code>事件，分析并提取每个出现的引用文本，并将其保存到一个竖线分隔CSV文件，这可能会帮助你得到你失踪的翻译。</p>
<h2 id="在与-magento-不同的机器上运行-vue-storefront-api-图像不起作用" tabindex="-1"><a class="header-anchor" href="#在与-magento-不同的机器上运行-vue-storefront-api-图像不起作用" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/recipes.html#running-vue-storefront-api-on-a-different-machine-than-magento-images-not-working" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>在与 magento 不同的机器上运行 vue-storefront-api / 图像不起作用</h2>
<p>当你把 vue-storefront-api 和 magento2 放在不同的服务器上分开时，需要通过网络文件夹将 vue-storefront-api 机器与 magento 媒体文件夹链接起来。<code>sshsfs</code>为此建议。建立网络连接后，需要在 vue-storefront-api 配置中指向正确的文件夹</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>"assetPath": "/../var/magento2-sample-data/pub/media", 
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>需要通过 vue-storefront-api 创建正确的产品图片。如果没有正确设置，图像将只是占位符，而不管其他设置是否有效，您可以看到正确同步的产品和类别。</p>
<h2 id="同步-magento-和-vue-storefront-api-服务器-修复-验证随机数时出错" tabindex="-1"><a class="header-anchor" href="#同步-magento-和-vue-storefront-api-服务器-修复-验证随机数时出错" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/basics/recipes.html#syncing-magento-and-vue-storefront-api-servers-fix-for-an-error-occurred-validating-the-nonce" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>同步 magento 和 vue-storefront-api 服务器/修复“验证随机数时出错”</h2>
<p>如果其中一台服务器落后另一台服务器超过 600 秒，则 JWT 令牌验证可能会出现问题。600 秒限制在 Magento 端由其<code>\Magento\Integration\Model\Oauth\Nonce\Generator::TIME_DEVIATION</code>. 要解决此问题，您需要确保两个服务器<code>date</code>命令显示相同的日期时间（或两者至少相差 10 分钟以下）。这可以通过使用<code>tzdata</code>包（sudo dpkg-reconfigure tzdata）或直接使用<code>date</code>包设置（例如：<code>sudo date --set &quot;23 Mar 2019 12:00:00&quot;</code>，但提供当前日期时间）来完成。</p>
</template>
