<template><h1 id="异步数据加载器" tabindex="-1"><a class="header-anchor" href="#异步数据加载器" aria-hidden="true">#</a> 异步数据加载器</h1>
<p>从 Vue Storefront 1.8 开始，有一个新的实验性 API 用于扩展服务器端数据获取。该库被调用<code>AsyncDataLoader</code>并由两个方法组成：<code>push</code>，用于将新的数据获取承诺排入<code>flush</code>队列，以及，用于执行所有排入队列的承诺。</p>
<p>Vue Storefront 的服务端渲染功能是按照一般的<a href="https://vuejs.org/v2/guide/ssr.html" target="_blank" rel="noopener noreferrer">Vue.js SSR 原则设计的 （打开新窗口）<OutboundLink/></a>. 每个根级页面（分配给一个路由）都包含一个特殊的<code>asyncData</code>方法，该方法在创建任何组件之前执行，只是为了用所有必要的数据填充 Vuex 状态。</p>
<p>然后在<code>window.__INITIAL_STATE__</code>对象内将预取的 Vuex 状态提供给客户端以对客户端数据进行水合。</p>
<p>因为<code>asyncData</code>方法是集中式的（每个路由一个），所以不可能从添加到 Vue Storefront 的主题的任何模块/自定义代码中注入任何数据预取方法。如果您在主题中创建了自己的版本<code>Product.vue</code>或<code>Category.vue</code>页面，您可能已经更改，<code>asyncData</code>但仅此而已。</p>
<p>所以我们有了 AsyncLoader 😃</p>
<h2 id="例子" tabindex="-1"><a class="header-anchor" href="#例子" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/data/data-loader.html#examples" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>例子</h2>
<p>看<code>src/module-template/hooks/beforeRegistration</code>一个例子：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> AsyncDataLoader <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@vue-storefront/core/lib/async-data-loader'</span>
  AsyncDataLoader<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token punctuation">{</span> <span class="token comment">// this is an example showing how to call data loader from another module</span>
    <span class="token function-variable function">execute</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> route<span class="token punctuation">,</span> store<span class="token punctuation">,</span> context <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
      <span class="token keyword">return</span> <span class="token keyword">new</span> <span class="token class-name">Promise</span> <span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">resolve<span class="token punctuation">,</span> reject</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
        store<span class="token punctuation">.</span><span class="token function">dispatch</span><span class="token punctuation">(</span><span class="token string">'example/dataloader'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">results</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
          <span class="token function">resolve</span><span class="token punctuation">(</span>results<span class="token punctuation">)</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span>
      <span class="token punctuation">}</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div><p>就这样！此处排队的操作将随每个 SSR 请求执行，<code>store.state.exampleDataFetchedByLoader</code>并将附加到 ，<code>window.__INITIAL_STATE__.exampleDataFetchedByLoader</code>以便您的数据可以在 SSR 模式下访问。</p>
<p>您可以通过检查提供的<code>route</code>或<code>context</code>对象来有选择地执行获取逻辑：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> AsyncDataLoader <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@vue-storefront/core/lib/async-data-loader'</span>
  AsyncDataLoader<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token punctuation">{</span> <span class="token comment">// this is an example showing how to call data loader from another module</span>
    <span class="token function-variable function">execute</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> route<span class="token punctuation">,</span> store<span class="token punctuation">,</span> context <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
      <span class="token keyword">return</span> <span class="token keyword">new</span> <span class="token class-name">Promise</span> <span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">resolve<span class="token punctuation">,</span> reject</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>route<span class="token punctuation">.</span>name <span class="token operator">===</span> <span class="token string">'bundle-product'</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
          store<span class="token punctuation">.</span><span class="token function">dispatch</span><span class="token punctuation">(</span><span class="token string">'example/dataloader'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">results</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
            <span class="token function">resolve</span><span class="token punctuation">(</span>results<span class="token punctuation">)</span>
          <span class="token punctuation">}</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
          <span class="token function">resolve</span><span class="token punctuation">(</span><span class="token keyword">null</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
      <span class="token punctuation">}</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br></div></div><p>该<code>context</code>对象是<code>Vue.prototype.$ssrContext</code>，它等于<code>context</code>对象传递给<code>asyncData</code>方法：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>    <span class="token keyword">const</span> context <span class="token operator">=</span> <span class="token punctuation">{</span>
      url<span class="token operator">:</span> req<span class="token punctuation">.</span>url<span class="token punctuation">,</span>
      output<span class="token operator">:</span> <span class="token punctuation">{</span>
        <span class="token function-variable function">prepend</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token parameter">context</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span> <span class="token keyword">return</span> <span class="token string">''</span> <span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token comment">// these functions can be replaced in the Vue components to append or prepend some content AFTER all other things are rendered. So in this function You may call: output.prepend() { return context.renderStyles() } to attach styles</span>
        <span class="token function-variable function">append</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token parameter">context</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span> <span class="token keyword">return</span> <span class="token string">''</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
        <span class="token function-variable function">appendHead</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token parameter">context</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span> <span class="token keyword">return</span> <span class="token string">''</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
        template<span class="token operator">:</span> <span class="token string">'default'</span><span class="token punctuation">,</span>
        cacheTags<span class="token operator">:</span> <span class="token keyword">null</span>
      <span class="token punctuation">}</span><span class="token punctuation">,</span>
      server<span class="token operator">:</span> <span class="token punctuation">{</span>
        app<span class="token operator">:</span> app<span class="token punctuation">,</span>
        response<span class="token operator">:</span> res<span class="token punctuation">,</span>
        request<span class="token operator">:</span> req
      <span class="token punctuation">}</span><span class="token punctuation">,</span>
      meta<span class="token operator">:</span> <span class="token keyword">null</span><span class="token punctuation">,</span>
      vs<span class="token operator">:</span> <span class="token punctuation">{</span>
        config<span class="token operator">:</span> config<span class="token punctuation">,</span>
        storeCode<span class="token operator">:</span> req<span class="token punctuation">.</span><span class="token function">header</span><span class="token punctuation">(</span><span class="token string">'x-vs-store-code'</span><span class="token punctuation">)</span> <span class="token operator">?</span> req<span class="token punctuation">.</span><span class="token function">header</span><span class="token punctuation">(</span><span class="token string">'x-vs-store-code'</span><span class="token punctuation">)</span> <span class="token operator">:</span> process<span class="token punctuation">.</span>env<span class="token punctuation">.</span><span class="token constant">STORE_CODE</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br></div></div><p>正如您可能在上下文对象中看到的，您的模块可以访问<code>Express.js</code>app (thru <code>context.server</code>)！</p>
</template>
