<template><h2 id="从-elasticsearch-获取数据" tabindex="-1"><a class="header-anchor" href="#从-elasticsearch-获取数据" aria-hidden="true">#</a> 从 ElasticSearch 获取数据</h2>
<p>Vue Storefront 将大部分目录数据存储在 Elasticsearch 数据存储中。请看一下我们的架构图：</p>
<p><img src="https://docs.vuestorefront.io/v1/assets/img/Vue-storefront-architecture.c0baad07.png" alt="架构图">.</p>
<p>要正确访问 Elasticsearch 数据，您应该实现特定的 Vuex 操作。这是<a href="https://github.com/vuestorefront/vue-storefront/blob/master/core/modules/catalog/store/category/actions.ts#L40" target="_blank" rel="noopener noreferrer">获取数据<OutboundLink/></a>的<a href="https://github.com/vuestorefront/vue-storefront/blob/master/core/modules/catalog/store/category/actions.ts#L40" target="_blank" rel="noopener noreferrer">vuex 操作<OutboundLink/></a>示例<a href="https://github.com/vuestorefront/vue-storefront/blob/master/core/modules/catalog/store/category/actions.ts#L40" target="_blank" rel="noopener noreferrer"> （打开新窗口）<OutboundLink/></a>：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> quickSearchByQuery <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@vue-storefront/core/lib/search'</span>
<span class="token keyword">import</span> createCategoryListQuery <span class="token keyword">from</span> <span class="token string">'@vue-storefront/core/modules/catalog/helpers/createCategoryListQuery'</span>

   <span class="token doc-comment comment">/**
   * Load categories within specified parent
   * <span class="token keyword">@param</span> <span class="token class-name"><span class="token punctuation">{</span>Object<span class="token punctuation">}</span></span> <span class="token parameter">commit</span> promise
   * <span class="token keyword">@param</span> <span class="token class-name"><span class="token punctuation">{</span>Object<span class="token punctuation">}</span></span> <span class="token parameter">parent</span> parent category
   */</span>
  <span class="token keyword">async</span> <span class="token function">list</span> <span class="token punctuation">(</span><span class="token punctuation">{</span> commit<span class="token punctuation">,</span> state<span class="token punctuation">,</span> dispatch <span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> parent <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">,</span> key <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">,</span> value <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">,</span> level <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">,</span> onlyActive <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">,</span> onlyNotEmpty <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">,</span> size <span class="token operator">=</span> <span class="token number">4000</span><span class="token punctuation">,</span> start <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">,</span> sort <span class="token operator">=</span> <span class="token string">'position:asc'</span><span class="token punctuation">,</span> includeFields <span class="token operator">=</span> config<span class="token punctuation">.</span>entities<span class="token punctuation">.</span>optimize <span class="token operator">?</span> config<span class="token punctuation">.</span>entities<span class="token punctuation">.</span>category<span class="token punctuation">.</span>includeFields <span class="token operator">:</span> <span class="token keyword">null</span><span class="token punctuation">,</span> excludeFields <span class="token operator">=</span> config<span class="token punctuation">.</span>entities<span class="token punctuation">.</span>optimize <span class="token operator">?</span> config<span class="token punctuation">.</span>entities<span class="token punctuation">.</span>category<span class="token punctuation">.</span>excludeFields <span class="token operator">:</span> <span class="token keyword">null</span><span class="token punctuation">,</span> skipCache <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">,</span> updateState <span class="token operator">=</span> <span class="token boolean">true</span> <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> <span class="token punctuation">{</span> searchQuery<span class="token punctuation">,</span> isCustomizedQuery <span class="token punctuation">}</span> <span class="token operator">=</span> <span class="token function">createCategoryListQuery</span><span class="token punctuation">(</span><span class="token punctuation">{</span> parent<span class="token punctuation">,</span> level<span class="token punctuation">,</span> key<span class="token punctuation">,</span> value<span class="token punctuation">,</span> onlyActive<span class="token punctuation">,</span> onlyNotEmpty <span class="token punctuation">}</span><span class="token punctuation">)</span>
    <span class="token keyword">const</span> shouldLoadCategories <span class="token operator">=</span> skipCache <span class="token operator">||</span> <span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token operator">!</span>state<span class="token punctuation">.</span>list <span class="token operator">||</span> state<span class="token punctuation">.</span>list<span class="token punctuation">.</span>length <span class="token operator">===</span> <span class="token number">0</span><span class="token punctuation">)</span> <span class="token operator">||</span> isCustomizedQuery<span class="token punctuation">)</span>

    <span class="token keyword">if</span> <span class="token punctuation">(</span>shouldLoadCategories<span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">const</span> resp <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">quickSearchByQuery</span><span class="token punctuation">(</span><span class="token punctuation">{</span> entityType<span class="token operator">:</span> <span class="token string">'category'</span><span class="token punctuation">,</span> query<span class="token operator">:</span> searchQuery<span class="token punctuation">,</span> sort<span class="token punctuation">,</span> size<span class="token punctuation">,</span> start<span class="token punctuation">,</span> includeFields<span class="token punctuation">,</span> excludeFields <span class="token punctuation">}</span><span class="token punctuation">)</span>

      <span class="token keyword">if</span> <span class="token punctuation">(</span>updateState<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">await</span> <span class="token function">dispatch</span><span class="token punctuation">(</span><span class="token string">'registerCategoryMapping'</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> categories<span class="token operator">:</span> resp<span class="token punctuation">.</span>items <span class="token punctuation">}</span><span class="token punctuation">)</span>

        <span class="token function">commit</span><span class="token punctuation">(</span>types<span class="token punctuation">.</span><span class="token constant">CATEGORY_UPD_CATEGORIES</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token operator">...</span>resp<span class="token punctuation">,</span> includeFields<span class="token punctuation">,</span> excludeFields <span class="token punctuation">}</span><span class="token punctuation">)</span>
        EventBus<span class="token punctuation">.</span><span class="token function">$emit</span><span class="token punctuation">(</span><span class="token string">'category-after-list'</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> query<span class="token operator">:</span> searchQuery<span class="token punctuation">,</span> sort<span class="token punctuation">,</span> size<span class="token punctuation">,</span> start<span class="token punctuation">,</span> list<span class="token operator">:</span> resp <span class="token punctuation">}</span><span class="token punctuation">)</span>
      <span class="token punctuation">}</span>

      <span class="token keyword">return</span> resp
    <span class="token punctuation">}</span>

    <span class="token keyword">const</span> list <span class="token operator">=</span> <span class="token punctuation">{</span> items<span class="token operator">:</span> state<span class="token punctuation">.</span>list<span class="token punctuation">,</span> total<span class="token operator">:</span> state<span class="token punctuation">.</span>list<span class="token punctuation">.</span>length <span class="token punctuation">}</span>

    <span class="token keyword">if</span> <span class="token punctuation">(</span>updateState<span class="token punctuation">)</span> <span class="token punctuation">{</span>
      EventBus<span class="token punctuation">.</span><span class="token function">$emit</span><span class="token punctuation">(</span><span class="token string">'category-after-list'</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> query<span class="token operator">:</span> searchQuery<span class="token punctuation">,</span> sort<span class="token punctuation">,</span> size<span class="token punctuation">,</span> start<span class="token punctuation">,</span> list <span class="token punctuation">}</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span>

    <span class="token keyword">return</span> list
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br></div></div><p>如您所见，我们使用的是<a href="https://github.com/vuestorefront/vue-storefront/blob/master/core/lib/search.ts#L31" target="_blank" rel="noopener noreferrer">quickSearchByQuery （打开新窗口）<OutboundLink/></a>用于执行搜索。这种方法非常有趣，因为：</p>
<ul>
<li>它使用<code>searchQuery</code>查询对象，该对象能够以通用方式应用过滤器。</li>
<li>它确实将接收到的数据缓存到<code>localForage</code>集合中，命名为<code>elasticCache</code>; 使用相同的 queryObject 的下一次调用将直接从浏览器存储返回数据，而不是访问服务器。</li>
</ul>
<p>我们不会在这一步构建另一个 Elasticsearch 查询。我们使用包含所有必要过滤器和搜索文本的搜索层对象。ES 查询在发送 Elasticsearch 请求之前使用强大的 bodybuilder 包构建。请查看<a href="https://github.com/danpaz/bodybuilder" target="_blank" rel="noopener noreferrer">参考文档以获取更多选项 （打开新窗口）<OutboundLink/></a>.</p>
</template>
