<template><h1 id="支付网关集成" tabindex="-1"><a class="header-anchor" href="#支付网关集成" aria-hidden="true">#</a> 支付网关集成</h1>
<p>Vue Storefront 是一个与平台无关的应用程序。这意味着它几乎可以连接到任何电子商务后端。同时，大多数现有的电子商务平台使用某种前端钩子集成支付网关（PG）：</p>
<ul>
<li>部分网关由 iframe 组件集成</li>
<li>其他的则是通过 JavaScript 片段等注入的。</li>
</ul>
<p>在这种情况下，您可以使用 PWA 修改支付网关的情况很少见，而无需自己创建集成代码。</p>
<h2 id="社区资源" tabindex="-1"><a class="header-anchor" href="#社区资源" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/integrations/payment-gateway.html#community-resources" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>社区资源</h2>
<p>我们的社区成员创建了一些非常酷的文档和支付模块的参考实现您可以并且可能应该基于：</p>
<ul>
<li>博客文章：<a href="https://www.develodesign.co.uk/news/development-of-the-paypal-module-for-vue-storefront/" target="_blank" rel="noopener noreferrer">如何创建 VS 1.6 支付模块（打开新窗口）<OutboundLink/></a></li>
<li>Paypal 集成：<a href="https://github.com/develodesign/vsf-payment-paypal" target="_blank" rel="noopener noreferrer">由 Develodesign 提供的 Paypal 集成（打开新窗口）<OutboundLink/></a></li>
<li>Braintree 集成：<a href="https://github.com/danrcoull/vsf-payment-braintree" target="_blank" rel="noopener noreferrer">Daniel Coull 的 Braintree 集成（打开新窗口）<OutboundLink/></a></li>
</ul>
<h2 id="前端集成" tabindex="-1"><a class="header-anchor" href="#前端集成" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/integrations/payment-gateway.html#frontend-integration" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>前端集成</h2>
<p>第一步是创建一个<a href="https://docs.vuestorefront.io/v1/guide/modules/introduction.html" target="_blank" rel="noopener noreferrer">Vue Storefront 模块<OutboundLink/></a>以在前端集成支付提供商。任何支付处理逻辑 UI 都通过模块单独处理。对于支付模块的最基本版本，“src/modules/payment-cash-on-delivery”。</p>
<ul>
<li>支付模块（如适用）应接住<code>checkout-payment-method-changed</code>通风口。如果付款方式代码是所需的代码，那么您可以选择将任何组件动态注入结帐时的订单审查部分，例如，信用卡输入字段、付款方式信息等。</li>
<li><code>checkout-before-placeOrder</code>在下订单之前，您需要捕捉事件并执行付款方式所需的任何处理。</li>
<li>您需要<code>checkout-do-placeOrder</code>使用可选的有效负载发出事件以完成放置订单过程。</li>
<li>要显示您的付款方式，请将其添加到 storage 中的 Payment Methods 集合<code>app.\$store.state.payment.methods.push(paymentMethodConfig)</code>。</li>
<li>不再需要时取消注册任何事件。</li>
<li>为了明确增长的扩展，应明确命名付款扩展 <code>payment-{VENDOR}-{PAYMENT_METHOD}</code></li>
</ul>
<h3 id="货到付款示例" tabindex="-1"><a class="header-anchor" href="#货到付款示例" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/integrations/payment-gateway.html#cash-on-delivery-example" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>货到付款示例</h3>
<p>这是“货到付款”付款方式主要逻辑的示例。它被放置在<code>src/modules/payment-cash-on-deliver/hooks/afterRegistration.ts</code>通常是注册自定义事件钩子的一个很好的入口点中：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> InfoComponent <span class="token keyword">from</span> <span class="token string">'../components/Info.vue'</span>
<span class="token keyword">import</span> config <span class="token keyword">from</span> <span class="token string">'config'</span>

<span class="token keyword">export</span> <span class="token keyword">function</span> <span class="token function">afterRegistration</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> Vue<span class="token punctuation">,</span> config<span class="token punctuation">,</span> store<span class="token punctuation">,</span> isServer <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token comment">// Place the order. Payload is empty as we don't have any specific info to add for this payment method '{}'</span>
  <span class="token keyword">const</span> <span class="token function-variable function">placeOrder</span> <span class="token operator">=</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    EventBus<span class="token punctuation">.</span><span class="token function">$emit</span><span class="token punctuation">(</span><span class="token string">'checkout-do-placeOrder'</span><span class="token punctuation">,</span> <span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
  <span class="token punctuation">}</span>

  <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>isServer<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">// Update the methods</span>
    <span class="token keyword">let</span> paymentMethodConfig <span class="token operator">=</span> <span class="token punctuation">{</span>
      <span class="token string">'title'</span><span class="token operator">:</span> <span class="token string">'Cash on delivery'</span><span class="token punctuation">,</span>
      <span class="token string">'code'</span><span class="token operator">:</span> <span class="token string">'cashondelivery'</span><span class="token punctuation">,</span>
      <span class="token string">'cost'</span><span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span>
      <span class="token string">'cost_incl_tax'</span><span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span>
      <span class="token string">'default'</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
      <span class="token string">'offline'</span><span class="token operator">:</span> <span class="token boolean">true</span>
    <span class="token punctuation">}</span>
    rootStore<span class="token punctuation">.</span><span class="token function">dispatch</span><span class="token punctuation">(</span><span class="token string">'payment/addMethod'</span><span class="token punctuation">,</span> paymentMethodConfig<span class="token punctuation">)</span>

    <span class="token comment">// Mount the info component when required.</span>
    EventBus<span class="token punctuation">.</span><span class="token function">$on</span><span class="token punctuation">(</span><span class="token string">'checkout-payment-method-changed'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token parameter">paymentMethodCode</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
      <span class="token keyword">if</span> <span class="token punctuation">(</span>paymentMethodCode <span class="token operator">===</span> <span class="token string">'cashondelivery'</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token comment">// Register the handler for what happens when they click the place order button.</span>
        EventBus<span class="token punctuation">.</span><span class="token function">$on</span><span class="token punctuation">(</span><span class="token string">'checkout-before-placeOrder'</span><span class="token punctuation">,</span> placeOrder<span class="token punctuation">)</span>

        <span class="token comment">// Dynamically inject a component into the order review section (optional)</span>
        <span class="token keyword">const</span> Component <span class="token operator">=</span> Vue<span class="token punctuation">.</span><span class="token function">extend</span><span class="token punctuation">(</span>InfoComponent<span class="token punctuation">)</span>
        <span class="token keyword">const</span> componentInstance <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">Component</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span>
        componentInstance<span class="token punctuation">.</span><span class="token function">$mount</span><span class="token punctuation">(</span><span class="token string">'#checkout-order-review-additional'</span><span class="token punctuation">)</span>
      <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
        <span class="token comment">// unregister the extensions placeorder handler</span>
        EventBus<span class="token punctuation">.</span><span class="token function">$off</span><span class="token punctuation">(</span><span class="token string">'checkout-before-placeOrder'</span><span class="token punctuation">,</span> placeOrder<span class="token punctuation">)</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br></div></div><h3 id="更多例子" tabindex="-1"><a class="header-anchor" href="#更多例子" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/integrations/payment-gateway.html#more-examples" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>更多例子</h3>
<p>您可以找到更复杂的<a href="https://github.com/develodesign/vsf-payment-paypal" target="_blank" rel="noopener noreferrer">Paypal<OutboundLink/></a>解决方案<a href="https://github.com/develodesign/vsf-payment-paypal" target="_blank" rel="noopener noreferrer"> （打开新窗口）<OutboundLink/></a>关于我们的合作伙伴 - <strong>Develodesign</strong> github 和<a href="https://github.com/danrcoull/vsf-payment-braintree" target="_blank" rel="noopener noreferrer">Braintree（打开新窗口）<OutboundLink/></a></p>
<p>更多信息：</p>
<ul>
<li><a href="https://www.develodesign.co.uk/news/development-of-the-paypal-module-for-vue-storefront/" target="_blank" rel="noopener noreferrer">如何创建 VS 1.6 支付模块（打开新窗口）<OutboundLink/></a></li>
</ul>
<h2 id="后端集成" tabindex="-1"><a class="header-anchor" href="#后端集成" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/integrations/payment-gateway.html#backend-integration" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>后端集成</h2>
<p>在前端成功集成支付后，您将用户和交易发送到支付集成商。然后，我们需要取回支付令牌/标识符并在支付集成商通知我们交易完成后立即更新订单状态。</p>
<p>要存储您将从支付服务获得的交易信息，您可以发出一个事件：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>    <span class="token function">placeOrderWithPayload</span> <span class="token punctuation">(</span><span class="token parameter">payload</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">this</span><span class="token punctuation">.</span>$bus<span class="token punctuation">.</span><span class="token function">$emit</span><span class="token punctuation">(</span><span class="token string">'checkout-do-placeOrder'</span><span class="token punctuation">,</span> payload<span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><p>其中有效负载等于带有附加订单信息的 JSON 对象。此对象将与<code>order.payment_method_additional</code>属性中的订单对象一起传输到服务器 。</p>
<h3 id="订单工作流程-服务器端" tabindex="-1"><a class="header-anchor" href="#订单工作流程-服务器端" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/integrations/payment-gateway.html#the-order-workflow-server-side" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>订单工作流程 - 服务器端</h3>
<p>为了做到这一点，首先我们必须了解 Vue Storefront 是如何处理订单的。由于支持离线订单（订单可以在下单后立即发送，几分钟后甚至几小时后发送），Vue Storefront 将订单异步发送到服务器。</p>
<p>订单正在发送到<code>vue-storefront-api/api/order/create</code>端点。此 API 端点将订单推送到队列，然后通过名为<code>order_2_magento2.js</code>(o2m)的 cron 运行进程将订单从那里传输到电子商务后端。您将<code>o2m</code>在<code>vue-storefront-api/worker</code>文件夹中找到 的源代码。</p>
<p>如您所见，我们没有在下订单后立即获得后端的订单号。为了配对客户端订单 ID 和服务器端元数据，<code>order_2_magento.js</code>进程在<code>Redis</code>缓存中存储特殊的元数据条目：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>api<span class="token punctuation">.</span>cart<span class="token punctuation">.</span><span class="token function">order</span><span class="token punctuation">(</span><span class="token keyword">null</span><span class="token punctuation">,</span> cartId<span class="token punctuation">,</span> <span class="token punctuation">{</span>
  <span class="token string">"paymentMethod"</span><span class="token operator">:</span>
  <span class="token punctuation">{</span>
      <span class="token string">"method"</span><span class="token operator">:</span>orderData<span class="token punctuation">.</span>addressInformation<span class="token punctuation">.</span>payment_method_code<span class="token punctuation">,</span>
      <span class="token string">"additional_data"</span><span class="token operator">:</span>orderData<span class="token punctuation">.</span>addressInformation<span class="token punctuation">.</span>payment_method_additional
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">,</span> isThisAuthOrder<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token parameter">result</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  logger<span class="token punctuation">.</span><span class="token function">info</span><span class="token punctuation">(</span><span class="token constant">THREAD_ID</span><span class="token punctuation">,</span> result<span class="token punctuation">)</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
  <span class="token keyword">if</span><span class="token punctuation">(</span>job<span class="token punctuation">)</span> job<span class="token punctuation">.</span><span class="token function">progress</span><span class="token punctuation">(</span>currentStep<span class="token operator">++</span><span class="token punctuation">,</span> <span class="token constant">TOTAL_STEPS</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

  logger<span class="token punctuation">.</span><span class="token function">info</span><span class="token punctuation">(</span><span class="token constant">THREAD_ID</span> <span class="token operator">+</span> <span class="token string">'[OK] Order placed with ORDER ID'</span><span class="token punctuation">,</span> result<span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
  logger<span class="token punctuation">.</span><span class="token function">debug</span><span class="token punctuation">(</span><span class="token constant">THREAD_ID</span> <span class="token operator">+</span> result<span class="token punctuation">)</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
  redisClient<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">"order$$id$$"</span> <span class="token operator">+</span> orderData<span class="token punctuation">.</span>order_id<span class="token punctuation">,</span> <span class="token constant">JSON</span><span class="token punctuation">.</span><span class="token function">stringify</span><span class="token punctuation">(</span>
  <span class="token punctuation">{</span>
      platform_order_id<span class="token operator">:</span> result<span class="token punctuation">,</span>
      transmited<span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span>
      transmited_at<span class="token operator">:</span> <span class="token keyword">new</span> <span class="token class-name">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
      platform<span class="token operator">:</span> <span class="token string">'magento2'</span><span class="token punctuation">,</span>
      order<span class="token operator">:</span> orderData
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  redisClient<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">"order$$totals$$"</span> <span class="token operator">+</span> orderData<span class="token punctuation">.</span>order_id<span class="token punctuation">,</span> <span class="token constant">JSON</span><span class="token punctuation">.</span><span class="token function">stringify</span><span class="token punctuation">(</span>result<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token keyword">if</span><span class="token punctuation">(</span>job<span class="token punctuation">)</span> job<span class="token punctuation">.</span><span class="token function">progress</span><span class="token punctuation">(</span>currentStep<span class="token operator">++</span><span class="token punctuation">,</span> <span class="token constant">TOTAL_STEPS</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">return</span> <span class="token function">done</span><span class="token punctuation">(</span><span class="token keyword">null</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> magentoOrderId<span class="token operator">:</span> result<span class="token punctuation">,</span> transferedAt<span class="token operator">:</span> <span class="token keyword">new</span> <span class="token class-name">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br></div></div><p>如您所见，您可以通过访问本地Redis实例中的<strong>客户端</strong>订单ID来获取订单数据<code>order$$id$${clientsideorderid}</code>。</p>
<p>您可以<code>vue-storefront-api/src/api/sync.js</code>使用以下<code>check</code>方法检查：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> config<span class="token punctuation">,</span> db <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">let</span> syncApi <span class="token operator">=</span> <span class="token function">Router</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token doc-comment comment">/**
   * GET get stock item
   */</span>
  syncApi<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token string">'/order/:order_id'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token parameter">req<span class="token punctuation">,</span> res</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> Redis <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'redis'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">let</span> redisClient <span class="token operator">=</span> Redis<span class="token punctuation">.</span><span class="token function">createClient</span><span class="token punctuation">(</span>config<span class="token punctuation">.</span>redis<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// redis client</span>
    redisClient<span class="token punctuation">.</span><span class="token function">on</span><span class="token punctuation">(</span><span class="token string">'error'</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">err</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token comment">// workaround for https://github.com/NodeRedis/node_redis/issues/713</span>
      redisClient <span class="token operator">=</span> Redis<span class="token punctuation">.</span><span class="token function">createClient</span><span class="token punctuation">(</span>config<span class="token punctuation">.</span>redis<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// redis client</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

    redisClient<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token string">'order$$id$$'</span> <span class="token operator">+</span> req<span class="token punctuation">.</span><span class="token function">param</span><span class="token punctuation">(</span><span class="token string">'order_id'</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span>
      <span class="token parameter">err<span class="token punctuation">,</span>
      reply<span class="token punctuation">,</span></span>
    <span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">const</span> orderMetaData <span class="token operator">=</span> <span class="token constant">JSON</span><span class="token punctuation">.</span><span class="token function">parse</span><span class="token punctuation">(</span>reply<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token keyword">if</span> <span class="token punctuation">(</span>orderMetaData<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        orderMetaData<span class="token punctuation">.</span>order <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">;</span> <span class="token comment">// for security reasons we're just clearing out the real order data as it's set by `order_2_magento2.js`</span>
      <span class="token punctuation">}</span>
      <span class="token function">apiStatus</span><span class="token punctuation">(</span>res<span class="token punctuation">,</span> err <span class="token operator">?</span> err <span class="token operator">:</span> orderMetaData<span class="token punctuation">,</span> err <span class="token operator">?</span> <span class="token number">500</span> <span class="token operator">:</span> <span class="token number">200</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token keyword">return</span> syncApi<span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br></div></div><p>由于此方法通过仅包含客户端订单 ID 的非安全 URL 返回订单数据，因此<code>order</code>删除了一个属性以仅返回其订单的平台 ID。</p>
<h3 id="订单状态变化" tabindex="-1"><a class="header-anchor" href="#订单状态变化" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/integrations/payment-gateway.html#status-change-for-the-order" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>订单状态变化</h3>
<p>上面显示的示例是根据支付集成商的响应更新 Magento（或其他平台）订单状态的准备步骤。</p>
<p>首先，您需要在公共 URL 下添加特殊端点，该端点将从支付提供商处获取通知/状态。这是一个示例 [如何将自定义 API 端点添加到<code>vue-storefront-api</code>]（扩展 vue-storefront-api.md）。</p>
<p>要将 API 扩展添加到<code>vue-storefront-api</code>：</p>
<ol>
<li>内创建文件夹<code>src/api/extensions</code>。例如'custom-payment-method`</li>
<li>然后添加<code>index.js</code>文件并将API方法代码放入其中。我们正在使用 Express.js。这是扩展代码的样板/示例：</li>
</ol>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> apiStatus <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'../../../lib/util'</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> Router <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'express'</span><span class="token punctuation">;</span>

module<span class="token punctuation">.</span><span class="token function-variable function">exports</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> config<span class="token punctuation">,</span> db <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">let</span> mcApi <span class="token operator">=</span> <span class="token function">Router</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token doc-comment comment">/**
   * POST create an user
   */</span>
  mcApi<span class="token punctuation">.</span><span class="token function">post</span><span class="token punctuation">(</span><span class="token string">'/status'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token parameter">req<span class="token punctuation">,</span> res</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> notificationData <span class="token operator">=</span> req<span class="token punctuation">.</span>body<span class="token punctuation">;</span>
    <span class="token keyword">const</span> order_id <span class="token operator">=</span> <span class="token string">''</span><span class="token punctuation">;</span> <span class="token comment">// we should extract the client's order id from the notification status</span>
    <span class="token comment">/// ... business logic related to the status verification</span>

    <span class="token comment">// getting the data from Redis - the original order</span>
    <span class="token keyword">const</span> Redis <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'redis'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">const</span> Magento2Client <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">'magento2-rest-client'</span><span class="token punctuation">)</span><span class="token punctuation">.</span>Magento2Client<span class="token punctuation">;</span>

    <span class="token keyword">let</span> redisClient <span class="token operator">=</span> Redis<span class="token punctuation">.</span><span class="token function">createClient</span><span class="token punctuation">(</span>config<span class="token punctuation">.</span>redis<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// redis client</span>
    redisClient<span class="token punctuation">.</span><span class="token function">on</span><span class="token punctuation">(</span><span class="token string">'error'</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">err</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token comment">// workaround for https://github.com/NodeRedis/node_redis/issues/713</span>
      redisClient <span class="token operator">=</span> Redis<span class="token punctuation">.</span><span class="token function">createClient</span><span class="token punctuation">(</span>config<span class="token punctuation">.</span>redis<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// redis client</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

    redisClient<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token string">'order$$id$$'</span> <span class="token operator">+</span> order_id<span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">err<span class="token punctuation">,</span> reply</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">const</span> orderMetaData <span class="token operator">=</span> <span class="token constant">JSON</span><span class="token punctuation">.</span><span class="token function">parse</span><span class="token punctuation">(</span>reply<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token keyword">if</span> <span class="token punctuation">(</span>orderMetaData<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token comment">// now we can use the api client to update the order status in Magento</span>
        <span class="token keyword">const</span> client <span class="token operator">=</span> <span class="token function">Magento2Client</span><span class="token punctuation">(</span>config<span class="token punctuation">.</span>magento2<span class="token punctuation">.</span>api<span class="token punctuation">)</span><span class="token punctuation">;</span>
        client<span class="token punctuation">.</span><span class="token function">addMethods</span><span class="token punctuation">(</span><span class="token string">'invoice'</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">restClient</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
          <span class="token keyword">var</span> module <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">;</span>

          module<span class="token punctuation">.</span><span class="token function-variable function">create</span> <span class="token operator">=</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">return</span> restClient<span class="token punctuation">.</span><span class="token function">post</span><span class="token punctuation">(</span><span class="token string">'/invoice/create'</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// the real Magento2 endpoint should be here - this is just an example</span>
          <span class="token punctuation">}</span><span class="token punctuation">;</span>
          <span class="token keyword">return</span> module<span class="token punctuation">;</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        client<span class="token punctuation">.</span>invoice
          <span class="token punctuation">.</span><span class="token function">create</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
          <span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token parameter">result</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
            <span class="token function">apiStatus</span><span class="token punctuation">(</span>res<span class="token punctuation">,</span> result<span class="token punctuation">,</span> <span class="token number">200</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// just dump it to the browser, result = JSON object</span>
          <span class="token punctuation">}</span><span class="token punctuation">)</span>
          <span class="token punctuation">.</span><span class="token function">catch</span><span class="token punctuation">(</span><span class="token parameter">err</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
            <span class="token function">apiStatus</span><span class="token punctuation">(</span>res<span class="token punctuation">,</span> err<span class="token punctuation">,</span> <span class="token number">500</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
          <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">return</span> mcApi<span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br><span class="line-number">41</span><br><span class="line-number">42</span><br><span class="line-number">43</span><br><span class="line-number">44</span><br><span class="line-number">45</span><br><span class="line-number">46</span><br><span class="line-number">47</span><br><span class="line-number">48</span><br><span class="line-number">49</span><br><span class="line-number">50</span><br></div></div><ol>
<li>将扩展添加到<code>config/local.json</code>：</li>
</ol>
<div class="language-json ext-json line-numbers-mode"><pre v-pre class="language-json"><code>	<span class="token property">"registeredExtensions"</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token string">"custom-payment-method"</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><ol>
<li>重新启动 <code>vue-storefront-api</code></li>
<li>您的新 API 方法可<code>localhost:8080/api/ext/&lt;extension_name&gt;/&lt;extension_method&gt;</code>用于例如：<code>localhost:8080/api/ext/custom-payment-method/status</code></li>
</ol>
<p>在上面的这个扩展中，您可能希望通过客户端订单 ID（传递给支付服务并可能与通知一起返回）获取订单数据。然后<strong>您可以使用 Magento 2 API 来更新支付状态</strong>，可能是通过执行该 <code>invoice</code>方法。</p>
</template>
