<template><h1 id="vue-storefront-的国际化-i18n" tabindex="-1"><a class="header-anchor" href="#vue-storefront-的国际化-i18n" aria-hidden="true">#</a> Vue Storefront 的国际化 (i18n)</h1>
<p>Vue Storefront 允许您使用强大的<a href="http://kazupon.github.io/vue-i18n/" target="_blank" rel="noopener noreferrer">vue-i18n<OutboundLink/></a>翻译整个 UI<a href="http://kazupon.github.io/vue-i18n/" target="_blank" rel="noopener noreferrer"> （打开新窗口）<OutboundLink/></a>图书馆。</p>
<p>请在编写自己的主题/扩展时注意 i18n 问题，并牢记 i18n 支持，尤其是在向核心创建拉取请求时。</p>
<h2 id="在代码中使用-i18n" tabindex="-1"><a class="header-anchor" href="#在代码中使用-i18n" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/core-themes/translations.html#using-i18n-in-code" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>在代码中使用 i18n</h2>
<p>当你使用一个普通的 JS 模块时，你可以简单地使用翻译助手：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> i18n <span class="token keyword">from</span> <span class="token string">'@vue-storefront/i18n'</span><span class="token punctuation">;</span>
EventBus<span class="token punctuation">.</span><span class="token function">$emit</span><span class="token punctuation">(</span><span class="token string">'notification'</span><span class="token punctuation">,</span> <span class="token punctuation">{</span>
  type<span class="token operator">:</span> <span class="token string">'success'</span><span class="token punctuation">,</span>
  message<span class="token operator">:</span> i18n<span class="token punctuation">.</span><span class="token function">t</span><span class="token punctuation">(</span><span class="token string">'Product has been added to the cart!'</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
  action1<span class="token operator">:</span> <span class="token punctuation">{</span> label<span class="token operator">:</span> i18n<span class="token punctuation">.</span><span class="token function">t</span><span class="token punctuation">(</span><span class="token string">'OK'</span><span class="token punctuation">)</span><span class="token punctuation">,</span> action<span class="token operator">:</span> <span class="token string">'close'</span> <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><p>如果您正在使用<code>.vue</code>组件，那么使用 Vue 指令就更简单了<code>$t</code>：</p>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code>    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>span</span><span class="token punctuation">></span></span>
        {{ $t('Size guide') }}
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>span</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><p>对于所有辅助方法和指令，以及可用参数，请查看<a href="http://kazupon.github.io/vue-i18n/introduction.html" target="_blank" rel="noopener noreferrer">vue-i18n 文档 （打开新窗口）<OutboundLink/></a>.</p>
<h2 id="使用翻译" tabindex="-1"><a class="header-anchor" href="#使用翻译" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/core-themes/translations.html#working-with-translations" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>使用翻译</h2>
<p>翻译在<code>core/i18n/resource/i18n/en-US.csv</code>文件中提供，可以相应地扩展/覆盖<code>src/themes/{themename}/resource/i18n/en-US.csv</code>。</p>
<p>下面是一个例子<code>en-US.csv</code>的<code>en-US</code>语言环境：</p>
<div class="language-csv ext-csv line-numbers-mode"><pre v-pre class="language-csv"><code><span class="token value">"customMessage"</span><span class="token punctuation">,</span><span class="token value">"You can define or override translation messages here."</span>
<span class="token value">"welcomeMessage"</span><span class="token punctuation">,</span><span class="token value"> </span><span class="token value">"Welcome to Vue Storefront theme starter!"</span><span class="token punctuation">,</span>
<span class="token value">"In case of any problems please take a look at the docs. If you haven't found what you were looking for in docs feel free to ask your question on our Slack"</span><span class="token punctuation">,</span><span class="token value"> </span><span class="token value">"In case of any problems please take a look at the docs. If you haven't found what you were looking for in docs feel free to ask your question on our Slack"</span><span class="token punctuation">,</span>
<span class="token value">"Here are some links that can help you with developing your own theme"</span><span class="token punctuation">,</span><span class="token value"> </span><span class="token value">"Here are some links that can help you with developing your own theme"</span><span class="token punctuation">,</span>
<span class="token value">"Project structure"</span><span class="token punctuation">,</span><span class="token value"> </span><span class="token value">"Project structure"</span><span class="token punctuation">,</span>
<span class="token value">"Working with themes"</span><span class="token punctuation">,</span><span class="token value"> </span><span class="token value">"Working with themes"</span><span class="token punctuation">,</span>
<span class="token value">"Working with components"</span><span class="token punctuation">,</span><span class="token value"> </span><span class="token value">"Working with components"</span><span class="token punctuation">,</span>
<span class="token value">"Working with data"</span><span class="token punctuation">,</span><span class="token value"> </span><span class="token value">"Working with data"</span><span class="token punctuation">,</span>
<span class="token value">"Vue Storefront Logo"</span><span class="token punctuation">,</span><span class="token value"> </span><span class="token value">"Vue Storefront Logo"</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><p>当您在<code>en-US.csv</code>文件<code>src/themes/{themename}/resource/i18n/</code>夹中创建文件并覆盖一些消息时，例如：</p>
<div class="language-csv ext-csv line-numbers-mode"><pre v-pre class="language-csv"><code><span class="token value">"customMessage"</span><span class="token punctuation">,</span><span class="token value">"You can define or override translation messages here."</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><p>...您可能会期望它<code>$t('customMessage)</code>会返回<code>You can define or override translation messages here.</code>而不是<code>Here is the core message. that can be overwritten in the theme</code>. 就如此容易！😃</p>
</template>
