<template><h1 id="与-service-worker-合作" tabindex="-1"><a class="header-anchor" href="#与-service-worker-合作" aria-hidden="true">#</a> 与 Service Worker 合作</h1>
<p>我们使用 Service Worker 有两个主要目的：</p>
<ol>
<li>缓存静态和动态数据提要，使其<a href="https://developers.google.com/web/fundamentals/primers/service-workers/" target="_blank" rel="noopener noreferrer">离线可用（打开新窗口）<OutboundLink/></a></li>
<li>运行离线数据同步。</li>
</ol>
<p>为了实现第一点，我们使用<a href="https://github.com/GoogleChromeLabs/sw-precache" target="_blank" rel="noopener noreferrer">sw-precache （打开新窗口）<OutboundLink/></a>来自谷歌，其次，在<a href="https://www.google.pl/search?q=sw-toolbox&amp;oq=sw-toolbox&amp;aqs=chrome..69i57j69i60l3j0l2.1529j0j4&amp;sourceid=chrome&amp;ie=UTF-8" target="_blank" rel="noopener noreferrer">sw-toolbox 的<OutboundLink/></a>帮助下，Vanilla JS<a href="https://www.google.pl/search?q=sw-toolbox&amp;oq=sw-toolbox&amp;aqs=chrome..69i57j69i60l3j0l2.1529j0j4&amp;sourceid=chrome&amp;ie=UTF-8" target="_blank" rel="noopener noreferrer">（打开新窗口）<OutboundLink/></a></p>
<h2 id="让事情发生" tabindex="-1"><a class="header-anchor" href="#让事情发生" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/core-themes/service-workers.html#making-things-happen" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>让事情发生</h2>
<p>的 service-worker 源代码<code>vue-storefront</code>使用 Babel 预设进行了预编译，并且所有内容都存储在<code>src/{themename}/service-worker/index.js</code>. 此文件附加到<code>service-worker.js</code>由<code>sw-toolbox</code>.</p>
<p>更改 中的任何内容后<code>{themename}/service-worker/index.js</code>，尽管您处于<code>yarn dev</code>自动重新加载模式，但您需要做两件事：</p>
<ol>
<li>重新编译应用程序（重新生成 service-worker）： <code>yarn build</code></li>
<li>在 Dev Tools 中重新加载 Service Worker（在 Chrome 中，只需单击**“取消注册”**并重新加载页面，就会安装一个新的 Service Worker）。</li>
</ol>
<p><img src="https://docs.vuestorefront.io/v1/assets/img/chrome-dev-console.3c88272d.png" alt="如何在 Chrome 中与 service-worker 一起工作"></p>
<h2 id="与应用程序的通信" tabindex="-1"><a class="header-anchor" href="#与应用程序的通信" aria-hidden="true">#</a> <a href="https://docs.vuestorefront.io/v1/guide/core-themes/service-workers.html#communication-with-the-app" target="_blank" rel="noopener noreferrer">#<OutboundLink/></a>与应用程序的通信</h2>
<p>应用程序可以使用事件总线与 Service Worker 对话，并且只能这样做。请看看<code>/core/lib/sw.js</code>我们哪里有以下方法：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">export</span> <span class="token keyword">function</span> <span class="token function">postMessage</span><span class="token punctuation">(</span><span class="token parameter">payload</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token string">'serviceWorker'</span> <span class="token keyword">in</span> navigator <span class="token operator">&amp;&amp;</span> navigator<span class="token punctuation">.</span>serviceWorker<span class="token punctuation">.</span>controller<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">// check if it's properly installed</span>
    navigator<span class="token punctuation">.</span>serviceWorker<span class="token punctuation">.</span>controller<span class="token punctuation">.</span><span class="token function">postMessage</span><span class="token punctuation">(</span>payload<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">return</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
    <span class="token comment">// no service workers supported push the queue manualy</span>
    <span class="token keyword">return</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div><p>它允许您向 Service Worker 发送数据。例如，当下单时 ( <code>/core/store/modules/checkout</code>)：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>  <span class="token doc-comment comment">/**
   * Add order to sync. queue
   * <span class="token keyword">@param</span> <span class="token class-name"><span class="token punctuation">{</span>Object<span class="token punctuation">}</span></span> <span class="token parameter">product</span> data format for products is described in /doc/ElasticSearch data formats.md
   */</span>
  <span class="token punctuation">[</span>types<span class="token punctuation">.</span><span class="token constant">CHECKOUT_PLACE_ORDER</span><span class="token punctuation">]</span> <span class="token punctuation">(</span><span class="token parameter">state<span class="token punctuation">,</span> order</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> ordersCollection <span class="token operator">=</span> StorageManager<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token string">'orders'</span><span class="token punctuation">)</span>
    <span class="token keyword">const</span> orderId <span class="token operator">=</span> entities<span class="token punctuation">.</span><span class="token function">uniqueEntityId</span><span class="token punctuation">(</span>order<span class="token punctuation">)</span> <span class="token comment">// timestamp as a order id is not the best we can do but it's enough</span>
    order<span class="token punctuation">.</span>id <span class="token operator">=</span> orderId<span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    order<span class="token punctuation">.</span>transmited <span class="token operator">=</span> <span class="token boolean">false</span>
    order<span class="token punctuation">.</span>created_at <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    order<span class="token punctuation">.</span>updated_at <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span>

    ordersCollection<span class="token punctuation">.</span><span class="token function">setItem</span><span class="token punctuation">(</span>orderId<span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> order<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">catch</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">reason</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
      console<span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span>reason<span class="token punctuation">)</span> <span class="token comment">// it doesn't work on SSR</span>
      sw<span class="token punctuation">.</span><span class="token function">postMessage</span><span class="token punctuation">(</span><span class="token punctuation">{</span> config<span class="token operator">:</span> config<span class="token punctuation">,</span> command<span class="token operator">:</span> types<span class="token punctuation">.</span><span class="token constant">CHECKOUT_PROCESS_QUEUE</span> <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token comment">// process checkout queue</span>
      console<span class="token punctuation">.</span><span class="token function">info</span><span class="token punctuation">(</span><span class="token string">'Order placed, orderId = '</span> <span class="token operator">+</span> orderId<span class="token punctuation">)</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token comment">// populate cache</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br></div></div></template>
